# Generated by Django 5.0.3 on 2024-04-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newswrite',
            name='summary',
            field=models.CharField(default='exist', max_length=150),
            preserve_default=False,
        ),
    ]
