# Generated by Django 5.0.3 on 2024-04-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_newswrite_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newswrite',
            name='heading',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newswrite',
            name='summary',
            field=models.CharField(max_length=200),
        ),
    ]
