# Generated by Django 5.0.3 on 2024-04-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_newswrite_heading_alter_newswrite_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newswrite',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
