# Generated by Django 5.0.3 on 2024-04-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_technology_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='heading',
            field=models.CharField(max_length=100),
        ),
    ]
